name: pocaduck
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pyarrow=20.0.0
  - pandas=2.2.3
  - numpy=2.2.5
  - python-duckdb=1.2.2
  # Storage support
  - aws-sdk-cpp
  - azure-storage-blobs-cpp
  - libgoogle-cloud-storage
  # Dev dependencies
  - pytest
